# Generated by Django 6.0.1 on 2026-04-14 21:49

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def seed_demo_assets(apps, schema_editor):
    AssetCategory = apps.get_model("landing", "AssetCategory")
    Producer = apps.get_model("landing", "Producer")
    Farm = apps.get_model("landing", "Farm")
    BiologicalAsset = apps.get_model("landing", "BiologicalAsset")
    AssetStatusHistory = apps.get_model("landing", "AssetStatusHistory")

    categories = {
        "cattle_lot": AssetCategory.objects.update_or_create(
            code="cattle_lot",
            defaults={
                "name": "Lote ganadero",
                "description": "Activo agrupado para demo de microinversion.",
                "is_active": True,
            },
        )[0],
        "individual_cattle": AssetCategory.objects.update_or_create(
            code="individual_cattle",
            defaults={
                "name": "Animal individual",
                "description": "Activo individual para demo academica.",
                "is_active": True,
            },
        )[0],
    }

    producers = {
        "P-001": Producer.objects.update_or_create(
            document="P-001",
            defaults={
                "name": "Ganaderia El Roble",
                "phone": "3001002001",
                "email": "roble@agrotech.demo",
                "status": "active",
            },
        )[0],
        "P-002": Producer.objects.update_or_create(
            document="P-002",
            defaults={
                "name": "Hacienda Santa Lucia",
                "phone": "3001002002",
                "email": "santalucia@agrotech.demo",
                "status": "active",
            },
        )[0],
        "P-003": Producer.objects.update_or_create(
            document="P-003",
            defaults={
                "name": "Agropecuaria La Esperanza",
                "phone": "3001002003",
                "email": "esperanza@agrotech.demo",
                "status": "active",
            },
        )[0],
    }

    farms = {
        "FARM-001": Farm.objects.update_or_create(
            code="FARM-001",
            defaults={
                "producer": producers["P-001"],
                "name": "Finca El Roble",
                "municipality": "Monteria",
                "department": "Cordoba",
                "location": "Km 14 via Cerete",
                "hectares": 84,
                "status": "active",
            },
        )[0],
        "FARM-002": Farm.objects.update_or_create(
            code="FARM-002",
            defaults={
                "producer": producers["P-002"],
                "name": "Finca Santa Lucia",
                "municipality": "Sincelejo",
                "department": "Sucre",
                "location": "Corregimiento La Arena",
                "hectares": 65,
                "status": "active",
            },
        )[0],
        "FARM-003": Farm.objects.update_or_create(
            code="FARM-003",
            defaults={
                "producer": producers["P-003"],
                "name": "Finca La Esperanza",
                "municipality": "Planeta Rica",
                "department": "Cordoba",
                "location": "Vereda Nueva Union",
                "hectares": 92,
                "status": "active",
            },
        )[0],
    }

    assets = [
        {
            "code": "LOT-001",
            "name": "Lote Brahman Norte 01",
            "asset_type": "lot",
            "category": categories["cattle_lot"],
            "producer": producers["P-001"],
            "farm": farms["FARM-001"],
            "initial_weight": 420,
            "current_weight": 478,
            "initial_value": 28500000,
            "projected_value": 33100000,
            "estimated_return_pct": 16.14,
            "start_date": "2026-02-10",
            "estimated_sale_date": "2026-08-20",
            "status": "available",
            "description": "Lote de engorde con trazabilidad digital y seguimiento quincenal.",
            "tokenized_units": 120,
            "available_units": 24,
            "is_featured": True,
            "display_order": 1,
        },
        {
            "code": "IND-001",
            "name": "Novillo Tokenizado Atlas",
            "asset_type": "individual",
            "category": categories["individual_cattle"],
            "producer": producers["P-002"],
            "farm": farms["FARM-002"],
            "initial_weight": 355,
            "current_weight": 401,
            "initial_value": 6900000,
            "projected_value": 8020000,
            "estimated_return_pct": 16.23,
            "start_date": "2026-01-28",
            "estimated_sale_date": "2026-07-30",
            "status": "available",
            "description": "Animal individual orientado a inversion fraccionada de corto ciclo.",
            "tokenized_units": 40,
            "available_units": 11,
            "is_featured": True,
            "display_order": 2,
        },
        {
            "code": "LOT-002",
            "name": "Lote Ceba Premium 02",
            "asset_type": "lot",
            "category": categories["cattle_lot"],
            "producer": producers["P-003"],
            "farm": farms["FARM-003"],
            "initial_weight": 510,
            "current_weight": 568,
            "initial_value": 36200000,
            "projected_value": 41900000,
            "estimated_return_pct": 15.75,
            "start_date": "2026-02-18",
            "estimated_sale_date": "2026-09-01",
            "status": "available",
            "description": "Lote simplificado para la demo con control de peso y valorizacion.",
            "tokenized_units": 160,
            "available_units": 42,
            "is_featured": True,
            "display_order": 3,
        },
        {
            "code": "IND-002",
            "name": "Novilla Aurora",
            "asset_type": "individual",
            "category": categories["individual_cattle"],
            "producer": producers["P-001"],
            "farm": farms["FARM-001"],
            "initial_weight": 330,
            "current_weight": 379,
            "initial_value": 6200000,
            "projected_value": 7260000,
            "estimated_return_pct": 17.10,
            "start_date": "2026-02-04",
            "estimated_sale_date": "2026-08-05",
            "status": "available",
            "description": "Activo individual con seguimiento mensual y proyeccion de venta local.",
            "tokenized_units": 36,
            "available_units": 9,
            "is_featured": True,
            "display_order": 4,
        },
        {
            "code": "LOT-003",
            "name": "Lote Caribe Sostenible",
            "asset_type": "lot",
            "category": categories["cattle_lot"],
            "producer": producers["P-002"],
            "farm": farms["FARM-002"],
            "initial_weight": 460,
            "current_weight": 517,
            "initial_value": 30100000,
            "projected_value": 34800000,
            "estimated_return_pct": 15.61,
            "start_date": "2026-03-01",
            "estimated_sale_date": "2026-09-15",
            "status": "available",
            "description": "Lote orientado a narrativa ESG y control sanitario simplificado.",
            "tokenized_units": 140,
            "available_units": 28,
            "is_featured": True,
            "display_order": 5,
        },
        {
            "code": "IND-003",
            "name": "Toro Joven Titan",
            "asset_type": "individual",
            "category": categories["individual_cattle"],
            "producer": producers["P-003"],
            "farm": farms["FARM-003"],
            "initial_weight": 370,
            "current_weight": 425,
            "initial_value": 7100000,
            "projected_value": 8300000,
            "estimated_return_pct": 16.90,
            "start_date": "2026-02-22",
            "estimated_sale_date": "2026-08-28",
            "status": "available",
            "description": "Activo individual de alta visibilidad para la vitrina principal.",
            "tokenized_units": 48,
            "available_units": 13,
            "is_featured": True,
            "display_order": 6,
        },
    ]

    for asset_data in assets:
        asset, _ = BiologicalAsset.objects.update_or_create(
            code=asset_data["code"],
            defaults=asset_data,
        )
        AssetStatusHistory.objects.get_or_create(
            asset=asset,
            previous_status="",
            new_status=asset.status,
            notes="Registro inicial del activo para la demo AgroTech.",
        )


def unseed_demo_assets(apps, schema_editor):
    BiologicalAsset = apps.get_model("landing", "BiologicalAsset")
    AssetStatusHistory = apps.get_model("landing", "AssetStatusHistory")
    Farm = apps.get_model("landing", "Farm")
    Producer = apps.get_model("landing", "Producer")
    AssetCategory = apps.get_model("landing", "AssetCategory")

    codes = ["LOT-001", "IND-001", "LOT-002", "IND-002", "LOT-003", "IND-003"]
    AssetStatusHistory.objects.filter(asset__code__in=codes).delete()
    BiologicalAsset.objects.filter(code__in=codes).delete()
    Farm.objects.filter(code__in=["FARM-001", "FARM-002", "FARM-003"]).delete()
    Producer.objects.filter(document__in=["P-001", "P-002", "P-003"]).delete()
    AssetCategory.objects.filter(code__in=["cattle_lot", "individual_cattle"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'agro_asset_category',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('municipality', models.CharField(max_length=80)),
                ('department', models.CharField(max_length=80)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('hectares', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('active', 'Activa'), ('inactive', 'Inactiva'), ('maintenance', 'En mantenimiento')], default='active', max_length=20)),
            ],
            options={
                'db_table': 'agro_farm',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BiologicalAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('asset_type', models.CharField(choices=[('individual', 'Animal individual'), ('lot', 'Lote')], default='lot', max_length=20)),
                ('initial_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('initial_value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('projected_value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('estimated_return_pct', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('start_date', models.DateField()),
                ('estimated_sale_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('available', 'Disponible'), ('funded', 'Financiado'), ('in_production', 'En produccion'), ('sold', 'Vendido'), ('closed', 'Cerrado'), ('cancelled', 'Cancelado')], default='available', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('tokenized_units', models.PositiveIntegerField(default=1)),
                ('available_units', models.PositiveIntegerField(default=1)),
                ('is_featured', models.BooleanField(default=False)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='landing.assetcategory')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='landing.farm')),
            ],
            options={
                'db_table': 'agro_biological_asset',
                'ordering': ['display_order', 'estimated_sale_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AssetStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(blank=True, choices=[('draft', 'Borrador'), ('available', 'Disponible'), ('funded', 'Financiado'), ('in_production', 'En produccion'), ('sold', 'Vendido'), ('closed', 'Cerrado'), ('cancelled', 'Cancelado')], max_length=20)),
                ('new_status', models.CharField(choices=[('draft', 'Borrador'), ('available', 'Disponible'), ('funded', 'Financiado'), ('in_production', 'En produccion'), ('sold', 'Vendido'), ('closed', 'Cerrado'), ('cancelled', 'Cancelado')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_status_changes', to=settings.AUTH_USER_MODEL)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='landing.biologicalasset')),
            ],
            options={
                'db_table': 'agro_asset_status_history',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('document', models.CharField(max_length=30, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo'), ('suspended', 'Suspendido')], default='active', max_length=20)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='producer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'agro_producer',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='farm',
            name='producer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='farms', to='landing.producer'),
        ),
        migrations.AddField(
            model_name='biologicalasset',
            name='producer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='landing.producer'),
        ),
        migrations.RunPython(seed_demo_assets, unseed_demo_assets),
    ]
