# Generated by Django 6.0.1 on 2026-04-14 22:31

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from decimal import Decimal


def seed_tokenized_assets(apps, schema_editor):
    BiologicalAsset = apps.get_model("landing", "BiologicalAsset")
    TokenizedAsset = apps.get_model("landing", "TokenizedAsset")

    for asset in BiologicalAsset.objects.all():
        total_tokens = asset.tokenized_units or 1
        TokenizedAsset.objects.update_or_create(
            asset=asset,
            defaults={
                "total_tokens": total_tokens,
                "tokens_available": asset.available_units,
                "token_price": Decimal("500000.00"),
            },
        )


def unseed_tokenized_assets(apps, schema_editor):
    TokenizedAsset = apps.get_model("landing", "TokenizedAsset")
    TokenizedAsset.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_assetcategory_farm_biologicalasset_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenizedAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_tokens', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('tokens_available', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('token_price', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tokenization', to='landing.biologicalasset')),
            ],
            options={
                'db_table': 'agro_tokenized_asset',
                'ordering': ['asset__display_order', 'asset__name'],
            },
        ),
        migrations.CreateModel(
            name='TokenTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('price_per_token', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('transaction_type', models.CharField(choices=[('buy', 'Compra')], default='buy', max_length=20)),
                ('tokenized_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='landing.tokenizedasset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'agro_token_transaction',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TokenHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_holdings', to=settings.AUTH_USER_MODEL)),
                ('tokenized_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='landing.tokenizedasset')),
            ],
            options={
                'db_table': 'agro_token_holding',
                'ordering': ['user__username', 'tokenized_asset__asset__name'],
                'unique_together': {('user', 'tokenized_asset')},
            },
        ),
        migrations.RunPython(seed_tokenized_assets, unseed_tokenized_assets),
    ]
