# Generated by Django 6.0.1 on 2026-04-15 04:54

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_set_fixed_token_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract_id', models.CharField(max_length=80, unique=True)),
                ('certificate_id', models.CharField(max_length=80, unique=True)),
                ('tokens_acquired', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('participation_pct', models.DecimalField(decimal_places=4, max_digits=8)),
                ('investment_value_cop', models.DecimalField(decimal_places=2, max_digits=14)),
                ('estimated_return_pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.CharField(choices=[('active', 'Activo'), ('archived', 'Archivado')], default='active', max_length=20)),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('tokenized_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digital_contracts', to='landing.tokenizedasset')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='digital_contract', to='landing.tokentransaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digital_contracts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'agro_digital_contract',
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='BlockchainRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tx_hash', models.CharField(max_length=100, unique=True)),
                ('block_id', models.CharField(max_length=60, unique=True)),
                ('contract_hash', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmado en blockchain'), ('pending', 'Pendiente')], default='confirmed', max_length=20)),
                ('confirmed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='blockchain_record', to='landing.tokentransaction')),
                ('digital_contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='blockchain_record', to='landing.digitalcontract')),
            ],
            options={
                'db_table': 'agro_blockchain_record',
                'ordering': ['-confirmed_at'],
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agt_balance', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'agro_wallet',
            },
        ),
    ]
