# Generated by Codex on 2026-04-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landing", "0006_move_demo_farms_to_huila"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallet",
            name="physical_agt_balance",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="wallet",
            name="physical_wallet_payload",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="wallet",
            name="physical_wallet_last_uid",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="wallet",
            name="physical_wallet_synced_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
